spring:
  # DATABASE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/practicas
    username: practicas
    password: pr4ct1c4as
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

# LOGGING
logging:
  level:
    ROOT: INFO
    com.acciona.service.vacaciones: DEBUG